#!/bin/bash

export TF_CPP_MIN_LOG_LEVEL="2"

dataset=$1    # cifar10/mnist/svhn
seedmodel=$2  # path to starting model
bagfolder=$3  # new folder will be made to store bag of models here
order=$4      # file containing order of attacks
transfer=$5   # transfer of parameters (yes/no)
seedproxy=$6  # path to starting proxy model

# Make a copy of proxy seed for ending up with new adaptive proxy
temp=$(date -d "today" +"%s")
cp $seedproxy $temp
seedproxy=$temp

if [ $dataset == "mnist" ]
        then
                :
elif [ $dataset == "svhn" ]
        then
                :
elif [ $dataset == "cifar10" ]
        then
              	:
else
        echo "Invalid dataset! Exiting"
        exit
fi

mkdir -p $bagfolder

# Copy initial seed model to directory
# python fix.py $seedmodel
cp $seedmodel $bagfolder/1

echo "Seed proxy model will be stored by the name $seedproxy.hdf5"

COUNTER=1 # Counting models

seeddata=$(date -d "today" +"%s") # Required if cumulative data is to be used
sleep 2                           # Make sure name does not clash with prefix inside loop
attackssofar=""                   # Keep track of attacks so far

# Read order of attacks
while read attack
do
	echo "Running attack $COUNTER : $attack"

	prefix=$(date -d "today" +"%s") # Unique per dataset

	selectedmodel=$seedmodel
	# Pick model according to desired option
	if [ $transfer == "yes" ]; then
		selectedmodel=$bagfolder/$COUNTER
	fi

	# Make a copy of selected model for finetuning
	cp $selectedmodel $seeddata"model"

	# Update attacks so far
	attackssofar="$attackssofar,$attack"

	# Run adversarial training on proxy model (with distillation)
	python ../Code/train_model_proxy.py -e 1 -l 0.1 -s $seedproxy -m finetune -d $dataset -k True -t $bagfolder/$COUNTER -b 64 -a $attackssofar

	# Generate attack data using proxy model
	python ../Code/attack_proxy.py --dataset $dataset --batch_size 128 --model $seedproxy --attack_name $attackssofar --save_here $prefix --multiattacks --mode harden

	# Finetune target model against given attack, using data generated by proxy
	python ../Code/bagging.py --nb_epochs 1 --mode finetune --dataset $dataset --seed_model $seeddata"model" --model_dir $bagfolder --data_x $prefix"_x.npy" --data_y $prefix"_y.npy" --attack $attackssofar

	# Update model counter
	COUNTER=$[$COUNTER +1]

	# Add this model to bag
	mv $seeddata"model" $bagfolder/$COUNTER

done < $order

echo "Saving adaptive proxy as $seedproxy.hdf5"
mv $seedproxy "$seedproxy.hdf5"
